// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GeneralBlogApp.Models;

public partial class Article
{
    public int Id { get; set; }

    public int ArtId { get; set; }

    public int LangId { get; set; }

    public string Title { get; set; }

    public int CatId { get; set; }

    public string Summary { get; set; }

    public string MainImageUrl { get; set; }

    public string MainImageFileName { get; set; }

    public string MainImageAltTag { get; set; }

    public DateTime? MainImageUploadDate { get; set; }

    public bool? IsArchived { get; set; }

    public bool? IsPublished { get; set; }

    public string MetaKeywords { get; set; }

    public string MetaDescription { get; set; }

    public string MetaTitle { get; set; }

    public string Slug { get; set; }
}