// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GeneralBlogApp.Models;

public partial class Block
{
    public int Id { get; set; }

    public int BlockId { get; set; }

    public int LangId { get; set; }

    public int ArtId { get; set; }

    public int BlockOrder { get; set; }

    public string Text { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string ImageFileName { get; set; }

    public string ImageUrl { get; set; }

    public string ImageAltTag { get; set; }

    public DateTime? ImageUploadedDate { get; set; }

    public string ImageUploadedBy { get; set; }

    public string VideoLink { get; set; }
}