// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GeneralBlogApp.Models;

public partial class Category
{
    public int Id { get; set; }

    public int CatId { get; set; }

    public int LangId { get; set; }

    public string Name { get; set; }

    public string MetaDescription { get; set; }

    public string MetaKeywords { get; set; }
}